#pragma once

#define PUMP_PIN D2
#define SERIAL_BAUD 9600

#define WIFI_RETRY_DELAY 500
#define WIFI_MAX_RETRIES 2

#define PUMP_DEFAULT_EXECUTION_TIME_SECONDS 5
#define PUMP_MIN_EXECUTION_TIME_SECONDS 2
#define PUMP_MAX_EXECUTION_TIME_SECONDS 600
