#pragma once

#define PUMP_PIN D2
#define SERIAL_BAUD 9600

#define WIFI_RETRY_DELAY 500
#define WIFI_MAX_RETRIES 2

#define PUMP_DEFAULT_EXECUTION_TIME_SECONDS 5
#define PUMP_MIN_EXECUTION_TIME_SECONDS 2
#define PUMP_MAX_EXECUTION_TIME_SECONDS 600

#define EEPROM_SIZE 12
#define EEPROM_ADDR_PUMP_SECONDS 0
#define EEPROM_ADDR_PUMP_SCHEDULE 2
#define EEPROM_ADDR_DEVICE_TIME 4
